version: "3.9"

services:
  db:
    image: postgres:15
    container_name: student_portal_db
    environment:
      POSTGRES_DB: student_portal
      POSTGRES_USER: student_portal
      POSTGRES_PASSWORD: student_portal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student_portal -d student_portal"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: student_portal_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/student_portal
      SPRING_DATASOURCE_USERNAME: student_portal
      SPRING_DATASOURCE_PASSWORD: student_portal
    ports:
      - "8080:8080"

volumes:
  postgres_data: